# Generated by Django 4.0.2 on 2023-05-03 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_turffdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turffdetails',
            name='turff_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Turff_Owner',
        ),
    ]
