# Generated by Django 4.0.2 on 2023-05-06 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_turffdetails_turff_owner_delete_turff_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('s_time', models.TimeField()),
                ('e_time', models.TimeField()),
                ('amount', models.IntegerField()),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.turffdetails')),
            ],
        ),
    ]
