# Generated by Django 4.0.2 on 2023-05-06 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbooking',
            name='amount',
        ),
    ]
