# Generated by Django 4.0.2 on 2023-06-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tbooking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbooking',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
    ]
