# Generated by Django 4.0.2 on 2023-04-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='turffdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turff_name', models.CharField(max_length=30)),
                ('turff_address', models.TextField()),
                ('turff_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('contact', models.CharField(max_length=12)),
                ('court_fee', models.CharField(max_length=100)),
                ('court_size', models.CharField(max_length=50)),
                ('t_email', models.EmailField(max_length=50)),
            ],
        ),
    ]
