# Generated by Django 4.0.2 on 2023-04-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tadmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='turffdetails',
        ),
    ]
